name: SonarCloud 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore

      - name: Analyze with SonarCloud
        run: |
         dotnet tool install --global dotnet-sonarscanner --version 5.0.1.3006
         dotnet sonarscanner begin /o:romeosonarcloud /k:romeosonarcloud_repo1 /d:sonar.host.url=https://sonarcloud.io /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
         dotnet build ./WebApplicationRepo1.sln --configuration Release --no-restore
         dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
